name: Java CI/CD with Gradle and Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # ✅ Use the latest version

    - name: Set up JDK 11
      uses: actions/setup-java@v4  # ✅ Ensure correct Java version
      with:
        distribution: 'temurin'
        java-version: '11'
        check-latest: true

    - name: Verify Java installation
      run: java -version  # ✅ Check if Java is installed

    - name: Grant execute permissions to Gradle wrapper
      run: chmod +x gradlew  # ✅ Fix permissions

    - name: Build the project with Gradle
      run: ./gradlew build --no-daemon  # ✅ Build and generate JAR file

    - name: Verify that JAR file exists
      run: ls -l build/libs/  # ✅ Debug: List files in the build directory

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6  # ✅ Use latest version
      with:
        image: shakishnavi/implement_cicd
        tags: main-${{ github.run_number }}
        registry: docker.io
