name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # ✅ Use latest version

    - name: Set up JDK 11
      uses: actions/setup-java@v4  # ✅ Use latest version
      with:
        distribution: 'temurin'  # ✅ Specify the Java distribution
        java-version: '11'
        check-latest: true

    - name: Verify Java installation
      run: java -version  # ✅ Check if Java is installed correctly

    - name: Clean Gradle cache
      run: rm -rf ~/.gradle/caches/

    - name: Grant execute permissions to Gradle wrapper
      run: chmod +x gradlew  # ✅ Fix permission issue

    - name: Build with Gradle
      run: ./gradlew build --no-daemon


    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: shakishnavi/implement_cicd
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

